# Generated by Django 4.2.7 on 2023-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('product_vendor_code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('product_category', models.CharField(max_length=40, verbose_name='Категория')),
                ('product_sub_category', models.CharField(max_length=40, verbose_name='Подкатегория')),
                ('product_package', models.CharField(max_length=100, verbose_name='Упаковка')),
                ('product_net_weight', models.CharField(max_length=20, verbose_name='Вес нетто, г.')),
                ('product_full_category', models.CharField(max_length=40, verbose_name='Развёрнутая категория')),
                ('product_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
