# Generated by Django 4.2.7 on 2023-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цена, руб.'),
        ),
    ]
