# Generated by Django 4.2.7 on 2023-12-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_available_products_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
    ]
