# Generated by Django 4.2.7 on 2023-12-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, null=True, verbose_name='Цена, руб.'),
        ),
    ]
